[theme]
primaryColor = "#a855f7"
backgroundColor = "#05020a"
secondaryBackgroundColor = "#0e061a"
textColor = "#f3e8ff"
font = "sans serif"

[server]
headless = true
enableCORS = false
maxUploadSize = 25
